"""empty message

Revision ID: 42bf8af740e1
Revises: 6c15630349f3
Create Date: 2026-02-04 09:57:41.337502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42bf8af740e1'
down_revision = '6c15630349f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_29')
    with op.batch_alter_table('user_29', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('user_29')
    with op.batch_alter_table('collect_29', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_user_question_collect'))

    op.drop_table('collect_29')
    op.drop_table('email_captcha_29')
    op.drop_table('reply_29')
    op.drop_table('comment_29')
    with op.batch_alter_table('like_29', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_user_question_like'))

    op.drop_table('like_29')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_29',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_29.id'], name=op.f('like_29_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user_29.id'], name=op.f('like_29_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('like_29', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_question_like'), ['user_id', 'question_id'], unique=True)

    op.create_table('comment_29',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_29.id'], name='comment_29_ibfk_2'),
    sa.ForeignKeyConstraint(['question_id'], ['question_29.id'], name='comment_29_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reply_29',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_29.id'], name=op.f('reply_29_ibfk_2')),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_29.id'], name=op.f('reply_29_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('email_captcha_29',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('captcha', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('collect_29',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_29.id'], name=op.f('collect_29_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user_29.id'], name=op.f('collect_29_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('collect_29', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_question_collect'), ['user_id', 'question_id'], unique=True)

    op.create_table('user_29',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('join_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_29', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('question_29',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_29.id'], name=op.f('question_29_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
