"""empty message

Revision ID: 6c15630349f3
Revises: 88d39a898cff
Create Date: 2026-01-28 14:22:01.648325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c15630349f3'
down_revision = '88d39a898cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ques_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ques_id'], ['question_02.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_02.id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('question_favorites',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ques_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ques_id'], ['question_02.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_02.id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('question_likes',
    sa.Column('like_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ques_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ques_id'], ['question_02.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_02.id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    with op.batch_alter_table('question_02', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_02', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_02', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('points')
        batch_op.drop_column('post_count')

    with op.batch_alter_table('question_02', schema=None) as batch_op:
        batch_op.drop_column('comment_count')
        batch_op.drop_column('favorite_count')
        batch_op.drop_column('like_count')
        batch_op.drop_column('view_count')

    op.drop_table('question_likes')
    op.drop_table('question_favorites')
    op.drop_table('question_comments')
    # ### end Alembic commands ###
